# Generated by Django 5.2.17 on 2026-09-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': True},
        ),
    ]
